spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  batch:
    job:
      enabled: false
      scheduled: true
    initialize-schema: ${RTD_BATCH_INITIALIZE_SCHEMA:always}
  main:
    web-application-type: none
    allow-bean-definition-overriding: true

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

error-manager:
  enabled: true

logging:
  level:
    it.gov.pagopa.rtd.transaction_filter: ${LOG_LEVEL_RTD_TRANSACTION_FILTER:INFO}