#!/bin/sh

APP_ROOT="/app"
APP_BIN="$APP_ROOT/app.jar"

mkdir -p $ACQ_BATCH_TRX_INPUT_PATH
mkdir -p $ACQ_BATCH_OUTPUT_PATH
mkdir -p $ACQ_BATCH_TRX_LOGS_PATH
mkdir -p $ACQ_BATCH_HPAN_INPUT_PATH
mkdir -p $ACQ_BATCH_SENDER_ADEACK_OUTPUT_PATH
mkdir -p $ACQ_BATCH_FILE_REPORT_PATH

java -jar $APP_BIN
