apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtdmstransactionfilter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rtdmstransactionfilter
  template:
    metadata:
      labels:
        app: rtdmstransactionfilter
    spec:
      initContainers:
        - name: rtdmstransactionfilter-init
          image: busybox:1.34.1
          command: ["/bin/sh"]
          args: ["-c", "base64 -d /app_certs_in/publickey.asc.base64 > /app_workdir/publickey.asc"]
          volumeMounts:
            - name: certs-volume
              mountPath: /app_certs_in
              readOnly: true
            - name: workdir-volume
              mountPath: /app_workdir
      containers:
        - name: rtdmstransactionfilter
          image: cstardacr.azurecr.io/rtdmstransactionfilter
          volumeMounts:
            - name: certs-volume
              mountPath: /app_certs_in
              readOnly: true
            - name: workdir-volume
              mountPath: /app_workdir
          envFrom:
            - configMapRef:
                name: rtdtransactionfilter
          env:
            - name: ACQ_BATCH_INPUT_PUBLIC_KEYPATH
              value: /app_workdir/publickey.asc
            - name: HPAN_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rtdtransactionfilter
                  key: HPAN_SERVICE_API_KEY
            - name: HPAN_SERVICE_KEY_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rtdtransactionfilter
                  key: HPAN_SERVICE_KEY_STORE_PASSWORD
            - name: HPAN_SERVICE_TRUST_STORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rtdtransactionfilter
                  key: HPAN_SERVICE_TRUST_STORE_PASSWORD
          resources:
            limits:
              cpu: 2
              memory: 6Gi
            requests:
              cpu: 500m
              memory: 4Gi
          imagePullPolicy: Always
      volumes:
        - name: certs-volume
          secret:
            secretName: rtdtransactionfilter
            items:
            - key: HPAN_SERVICE_JKS_CONTENT_BASE64
              path: certs.jks.base64
            - key: HPAN_SERVICE_ENC_PUBLIC_KEY_ARMORED
              path: publickey.asc.base64
        - name: workdir-volume
          emptyDir: {}
