trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

#variables:
#  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
#  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:

  - task: SonarCloudPrepare@1
    displayName: 'Prepare SonarCloud analysis configuration'
    inputs:
      SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
      organization: '$(SONARCLOUD_ORG)'
      scannerMode: Other
      extraProperties: |
        sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
        sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
        sonar.exclusions='**/enums/**, **/model/**, **/*Constant*, **/*Config.java, **/*Scheduler.java, **/*Application.java, **/src/test/**, **/Dummy*.java'
  # - task: Maven@3
  #   inputs:
  #     mavenPomFile: 'pom.xml'
  #     goals: 'clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate '
  #     options: '-Dmaven.test.failure.ignore=true'
  #     publishJUnitResults: true
  #     testResultsFiles: '**/surefire-reports/TEST-*.xml'
  #     javaHomeOption: 'JDKVersion'
  #     mavenVersionOption: 'Default'
  #     mavenAuthenticateFeed: false
  #     effectivePomSkip: false
  #     sonarQubeRunAnalysis: false
  # - bash: xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ','); echo "##vso[task.setvariable variable=xmlReportPaths]$xmlReportPaths"
  #   displayName: finding jacoco.xml
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
      isJacocoCoverageReportXML: false
      sqMavenPluginVersionChoice: 'latest'
      
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'