trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: SonarCloudPrepare@1
    displayName: 'Prepare SonarCloud analysis configuration'
    inputs:
      SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
      organization: '$(SONARCLOUD_ORG)'
      scannerMode: Other

      extraProperties: |
        sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
        sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
        sonar.junit.reportPaths=target/surefire-reports
        sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-aggregate/jacoco.xml,target/site/jacoco/jacoco.xml
        sonar.exclusions='**/enums/**, **/model/**, **/*Constant*, **/*Config.java, **/*Scheduler.java, **/*Application.java, **/src/test/**, **/Dummy*.java'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 1.17
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: true
      isJacocoCoverageReportXML: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
