name: Upload asset

on:
  release:
    types: [published]

permissions:
  packages: write

jobs:
  upload:
    name: Upload asset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 #v3.13.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package

      - name: Upload
        run: gh release upload ${{ github.event.release.tag_name }} target/rtd-ms-transaction-filter.jar
