name: Upload asset

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      enabled:
        required: true
        type: string
        default: false

permissions:
  packages: write

jobs:
  release:
    name: Upload asset
    runs-on: ubuntu-latest
    if: inputs.enabled == 'true'
    environment: prod

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 #v3.13.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package

      - name: Upload
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/*.jar
