name: Upload asset

on:
  release:
    types: [published]

jobs:
  upload:
    name: Upload asset
    runs-on: ubuntu-latest
    permissions:
      contents: write # to modify a github release

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 #v4.2.1
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package

      - name: Upload
        run: gh release upload ${{ github.event.release.tag_name }} target/rtd-ms-transaction-filter.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
